name: "Check availabilities"
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "node"
      - run: ts-node check-availability.ts
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
